/* EX_1*/
SELECT Category_Name, Description From Categories ORDER BY Category_Name;
SELECT Contact_Name, COMPANY_NAME, CONTACT_TITLE FROM CUSTOMERS ORDER BY Phone;
SELECT FIRSTNAME, LASTNAME, HIREDATE FROM EMPLOYEES ORDER BY HIREDATE DESC;
SELECT ORDER_ID,ORDER_DATE, SHIPPED_DATE,CUSTOMER_ID,FREIGHT FROM ORDERS;
SELECT COMPANY_NAME, FAX, PHONE, HOME_PAGE FROM SUPPLIERS ORDER BY COUNTRY DESC, COMPANY_NAME;
SELECT TITLE, FIRSTNAME,LASTNAME FROM EMPLOYEES;

/* EX_2*/

SELECT COMPANY_NAME, CONTACT_NAME 
FROM CUSTOMERS 
WHERE CITY='Buenos Aires';

SELECT PRODUCT_NAME,UNIT_PRICE, QUANTITY_PER_UNIT
FROM PRODUCTS
WHERE UNITS_IN_STOCK=0;

SELECT ORDER_DATE, SHIPPED_DATE, CUSTOMER_ID, FREIGHT
FROM ORDERS
WHERE SHIPPED_DATE='19-May-1997';

SELECT FIRSTNAME, LASTNAME, COUNTRY
FROM EMPLOYEES
WHERE COUNTRY !='USA';

/* EX_3 */

SELECT  EMPLOYEE_ID,ORDER_ID,CUSTOMER_ID, REQUIRED_DATE, SHIPPED_DATE
FROM ORDERS
WHERE SHIPPED_DATE>REQUIRED_DATE;

SELECT CITY, COMPANY_NAME, CONTACT_NAME
FROM CUSTOMERS
WHERE CITY LIKE 'A%' OR  CITY LIKE 'B%';

SELECT ORDER_ID, ORDER_DATE,FREIGHT
FROM ORDERS
WHERE FREIGHT>500;

SELECT PRODUCT_NAME, UNITS_IN_STOCK, UNITS_ON_ORDER,REORDER_LEVEL
FROM PRODUCTS
WHERE REORDER_LEVEL > UNITS_IN_STOCK;

/* EX_4 */

SELECT COMPANY_NAME, CONTACT_NAME, FAX
FROM CUSTOMERS
WHERE FAX IS NOT NULL;


SELECT FIRSTNAME, LASTNAME
FROM EMPLOYEES
WHERE REPORTS_TO IS NULL;

/* EX_5 */

SELECT COMPANY_NAME, CONTACT_NAME,FAX
FROM CUSTOMERS
WHERE FAX IS NOT NULL
ORDER BY COMPANY_NAME;

SELECT ORDER_ID 
FROM ORDER_DETAILS
WHERE UNIT_PRICE=(SELECT  MAX(UNIT_PRICE)
FROM Order_DetailS);

--SELECT  TOTALPRICE, CUSTOMERS.COMPANY_NAME FROM (
SELECT SUM(UNIT_PRICE*QUANTITY*(1-DISCOUNT)) AS TotalPrice
FROM ORDER_DETAILS 
GROUP BY ORDER_ID;
--ORDER BY SUM(ORDER_DETAILS.UNIT_PRICE*QUANTITY*(1-ORDER_DETAILS.DISCOUNT)) DESC
--)Step1 INNER JOIN CUSTOMERS ON CUSTOMERS.CUSTOMER_ID=STEP1.CUSTOMER_ID
--WHERE ROWNUM=1;




